name:                fltkhs-themes
version:             0.1.0.0
github:              "deech/fltkhs-themes"
license:             BSD3
author:              "Aditya Siram"
maintainer:          "aditya.siram@gmail.com"
copyright:           "2018 Aditya Siram"
build-type:          Custom
extra-source-files:
- README.md
data-files:
- fonts/*.ttf
- images/*.png
extra-doc-files:
- doc/images/*.png
description:         Please see the README on Github at <https://github.com/deech/fltkhs-themes#readme>

custom-setup:
  dependencies:
  - base >= 4.4
  - Cabal >= 2.2.0.0 && < 3

library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - load-font >= 0.1.0.2
    - fltkhs >= 0.5.4.5
    - text >= 0.2 && < 1.3
    - vector >= 0.12.0.1
    - bytestring
  ghc-options: -Wall -fno-warn-name-shadowing
  when:
    - condition: os(linux)
      extra-libraries: fontconfig
